<?php
$categories = new CatalogueCategorie();
$liste = $categories->getListe();
?>

<nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix-top">
        <ul class="nav bs-docs-sidenav">
            <li class=""> <a href="#glyphicons">Catégories</a>
                <ul class="nav">
					<?php
					foreach ($liste as $categorie): /* @var $categorie CatalogueCategorie */
					?>
						<li><a href=""><?=$categorie->getCatalogue_categorie_libelle();?></a></li>
					<?php
					endforeach;
					?>
                </ul>
            </li>
<!--             <li class=""> <a href="#dropdowns">Dropdowns</a>
                <ul class="nav">
                    <li><a href="#dropdowns-example">Example</a></li>
                    <li class=""><a href="#dropdowns-alignment">Alignment</a></li>
                    <li><a href="#dropdowns-headers">Headers</a></li>
                    <li class=""><a href="#dropdowns-divider">Divider</a></li>
                    <li><a href="#dropdowns-disabled">Disabled menu items</a></li>
                </ul>
            </li>
            <li class=""> <a href="#btn-groups">Button groups</a>
                <ul class="nav">
                    <li><a href="#btn-groups-single">Basic example</a></li>
                    <li><a href="#btn-groups-toolbar">Button toolbar</a></li>
                    <li class=""><a href="#btn-groups-sizing">Sizing</a></li>
                    <li class=""><a href="#btn-groups-nested">Nesting</a></li>
                    <li><a href="#btn-groups-vertical">Vertical variation</a></li>
                    <li class=""><a href="#btn-groups-justified">Justified button groups</a></li>
                </ul>
            </li> -->
        </ul> <a class="back-to-top" href="#top"> Revenir en haut </a>
        <!-- <a href="#" class="bs-docs-theme-toggle" role="button"> Preview theme </a> -->

        </nav>