<?php
/**
 * Holds the default paginator view
 *
 *
 * @category backoffice
 * @package backoffice_paginators
 * @copyright RCWEB
 */
?>
<?php if ($this->pageCount): ?>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a class="text" href="<?php echo $this->url(array('page' => $this->previous)); ?>"> ← Précédent</a>
        <?php /* else: ?>
            <span class="disabled"> ← Previous</span>
        <?php */ endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            -
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
            <?php else: ?>
                <span class="current"><?php echo $page; ?></span>
            <?php endif; ?>

        <?php endforeach; ?>

        <!-- Next page link -->

        <?php if (isset($this->next)): ?>
            <a class="text" href="<?php echo $this->url(array('page' => $this->next)); ?>">Suivant →</a>
        <?php /* else: ?>
            <span class="disabled">Next →</span>
        <?php */ endif; ?>
<?php endif; ?>