<?php
/**
 * Error view
 *
 * @package views
 * @copyright RCWEB
 */
?>




<?php
$form = $this->form;
?>


<div class="container" id="contact-faq" style="margin-bottom:200px;">

  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 container-page-header">
    </div>
  </div>



<div class="row array-container pre-none forbidden" style="margin-top:120px;">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div id="errorpage" class="clearfix">
            <h1>Une erreur est survenue</h1>
            <p>
                Une erreur est survenue pendant le traitement de votre page.
            </p>
            <p><a class="alt" href="javascript:history.back();">← Page précédente</a></p>
        </div>
    </div>
</div>

<?php
// TDTODO : gestion des erreurs !!!!
echo $this->content; ?>


</div><!-- /.container main -->

