<?php
/**
 * Displays the forbidden error
 *
 * @category frontend
 * @package frontend_views
 * @subpackage frontend_views_error
 * @copyright RCWEB
 */
?>



<?php
$form = $this->form;
?>


<div class="container" id="contact-faq" style="margin-bottom:200px;">

  <div class="row">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 container-page-header">
    </div>
  </div>



<div class="row array-container pre-none forbidden" style="margin-top:120px;">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div id="errorpage" class="clearfix">
            <h1>Accès interdit</h1>
            <p>
                Vous n'avez pas les droits pour accéder à cette page.
            </p>
            <p><a class="alt" href="javascript:history.back();">← Page précédente</a></p>
        </div>
    </div>
</div>



</div><!-- /.container main -->



