<?php
/**
 * Default layout, used to render most parts of the application
 *
 * @package frontend_layouts
 * @copyright RCWEB
 */

//Configure the title
$this->headTitle()->setSeparator(' - ');
$this->headTitle('RCweb');

//Add generic CSS files
$this->headLink()->appendStylesheet($this->designUrl() . '/css/master.css');
// add jQuery ressources
$this->headLink()->appendStylesheet($this->designUrl() . '/css/jquery-ui.css');
$this->headScript()->appendFile($this->designUrl() . '/js/jquery.min.js');
$this->headScript()->appendFile($this->designUrl() . '/js/jquery-ui.min.js');

//Add the ZFDebug Toolbar only if enabled in app.ini
if(Zend_Controller_Front::getInstance()->hasPlugin('ZFDebug_Controller_Plugin_Debug')){
    $this->headScript()->appendFile($this->designUrl() . '/js/zfdebug.js');
    $this->headLink()->appendStylesheet($this->designUrl() . '/css/zfdebug.css');
}

//Autoload js files
$this->AutoloadResources();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-style-type" content="text/css" />
    <meta http-equiv="content-script-type" content="text/javascript" />

    <link rel="shortcut icon" type="image/ico" href="/images/favicon.png" />

    <?php echo $this->headTitle() . PHP_EOL;?>
    <?php echo $this->headLink() . PHP_EOL;?>
</head>
<body class="gallery">
    <?php echo $this->layout()->content;?>


    <?php echo $this->headScript() . PHP_EOL;?>
    <?php if(Zend_Registry::get('IS_PRODUCTION')) : ?>
        <?php echo $this->partial('partials/ga.phtml'); ?>
    <?php endif; ?>
</body>
</html>